config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root "pages#home"
  get "about" => "pages#about" #this creates the about path
  get "hotels" => "pages#hotels" 
  get "info" => "pages#info"
  get "chars" => "pages#chars"
  get "login" => "pages#login"
  get "hisname" => "pages#hisname"
  get "hername" => "pages#hername"
  get "contact" => "pages#contact"
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
belongs_to :user
has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>"}
validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
validates :description, presence:true
validates :image, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticable
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 
	has_many :pins, dependent: :destroy

	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) << :name
  devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def hotels
  end

  def info
  end

  def chars
  end

  def login
  end

  def hisname
  end

  def hername
  end

  def contact
  end


end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pin, only: [:show, :newgirl, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy, :show]
  respond_to :html

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end

  def show #ERIN--this is READ
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
    redirect_to @pin, notice: 'I Made a Page!'
    else 
    render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'I updated a page!'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  def newgirl
    @pin = Pin.new
    respond_with(@pin)
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div class="container">
   hello
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      
        <ul class="navbar-brand">
          <%= link_to "Home", root_path%>
        </ul>

    </div><!-- /.container -->


    <!-- Collect the nav links, forms, and other content for toggling -->
 
            
            <% if user_signed_in? %>
              
              <li><%= link_to "Help", about_path %></li>

              <li><%= link_to login_path do %>
                <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;Library
                <% end %>
              </li>

              <li><%= link_to new_pin_path do %>
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>New Story
                <% end %>
                </li>
              
              <li>
              <%= link_to "Quit", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure you're all done for today?" }%></li>
            
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path%></li>
              <%end%>

  </div><!-- /.container-fluid -->
</nav>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      
        <ul class="navbar-brand">
          <%= link_to "Home", root_path%>
        </ul>

    </div><!-- /.container -->


    <!-- Collect the nav links, forms, and other content for toggling


    REACTIVATE THE BELOW PART BY DELETING THE ABOVE LINE <--!!!!


    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            
            <% if user_signed_in? %>
              
              <li><%= link_to "Help", about_path %></li>

              <li><%= link_to current_user.name+"'s Tales", login_path %> 
              </li>

              <li><%= link_to new_pin_path do %>
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>New Story
                <% end %>
                </li>
              
              <li>
              <%= link_to "Quit", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure you're all done for today?" }%></li>
            
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path%></li>
              <%end%>
        
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oh My Stories!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<%= render 'layouts/header'%>
	<div class="container">
		
<% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>


		<%= yield %>
	</div>

</body>
</html>

app/views/pages/REALhome.html.erb
<html lang="en">  
  <head> 
	  
 </head>


 <body>
	<div class="jumbotron center">
	<h1><strong>Oh My Stories!</strong>
	 </h1>

   <h2>I create the stories of my dreams</h2>
	 
	 	<p>

		<div class="row">

		<div class="col-xs-6">
			<div class="imagetwist">
				<%= link_to(image_tag("dreaming.png"), chars_path) %>
			</div>
			</div>
		</div>

		<div class="col-xs-6">
			<div class="imageUNtwist">
				<% if user_signed_in? %>
						<%= link_to(image_tag("readsmaller.png"), login_path) %>
				<% else %>
            <%= link_to(image_tag("readsmaller.png"), new_user_session_path) %>
            <%end%>
      </div>
		</div>

		</p>
</div>
            
            





				

</body>

app/views/pages/about.html.erb
<html lang="en">  
 <head> 
	  
 </head>


 <body>

	<div class="jumbotron center">
		
		<h1>I have a question...</h1>
					
						<p class="text-left">
						How do I see my pins?
								<div class="dropdown" style="float: left;">
								  <button class="btn btn-default">
								  <td><%= link_to "Follow this link to see your pins", pins_path%></td><%= image_tag 'girlhead.jpg' %></button>
								  </button>
								  </ul>
								</div>
						</p><br></br><br></br>
						
					<p class="text-left">
						How do I print my story?
								<div class="dropdown" style="float: left;">
								  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true"><td><%= image_tag 'boyhead.jpg' %></td>
								    Just press the "Print" key after you create it.
								    <span class="caret"></span>
								  </button>
								  <ul class="dropdown-menu dropdown-menu-right" role="Answer" aria-labelledby="dropdownMenu1">
								    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Details: here's how you do it: text text <br>texttext text texttext text texttext</br>text texttext text texttext <br>text texttext text text</br></a></li>
								  </ul>
								</div>
						</p><br></br><br></br>

					<p class="text-left">
						Who is the illustrator?
								<div class="dropdown" style="float: left;">
								  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true"><td></td>
								    Here's information about the illustrator
								    <span class="caret"></span>
								  <%= image_tag 'girlhead.jpg' %></button>
									  <ul class="dropdown-menu dropdown-menu-right" role="Answer" aria-labelledby="dropdownMenu1">
									    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Details: text text text text text <br>texttext text text text text text text</br>text text text text texttext <br>text text text text text</br></a></li>
									  </ul>
								</div>
						</p><br></br> <br></br>
	
						<p class="text-left">
						How do I show all my friends my story?
								<div class="dropdown" style="float: left;">
								  <button class="btn btn-default dropdown-toggle" align="left" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true"><td><%= image_tag 'boyhead.jpg' %></td>
								    You can do this on the final page.
								    <span class="caret"></span>
								  </button>
								  <ul class="dropdown-menu dropdown-menu-right" role="Answer" aria-labelledby="dropdownMenu1">
								    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Details: here's how you do it: text text <br>texttext text texttext text texttext</br>text texttext text texttext <br>text texttext text text</br></a></li>
								  </ul>
								</div>
						</p><br></br><br></br>

					<p class="text-left">
						How do I change my settings?
								<div class="dropdown" style="float: left;">
								  <button class="btn btn-default">
								  <td><%= link_to "Follow this link to change your author name and other settings", edit_user_registration_path%></td><%= image_tag 'girlhead.jpg' %></button>
								  </button>
								  </ul>
								</div>
						</p><br></br><br></br>

						** Did we miss something? <%= link_to "Let us know!", contact_path%> **
	</div>
</body>

app/views/pages/chars.html.erb
<html lang="en">  
  <head> 
	  
 </head>


 <body>
	<div class="jumbotron center">
	<h1><strong>My Character</strong>
	 </h1>
	 
	 	<p>
		Is it a <%= link_to "Boy", "hisname", class: "btn btn-default btn-lg" %>
		&nbsp;or a&nbsp;
		<%= link_to "Girl", "hername", class: "btn btn-default btn-lg" %>
		?<p></p>
		<%= link_to(image_tag("boy.jpg"), hisname_path) %>
		<%= link_to(image_tag("girl.jpg"), hername_path) %>
		</p>
</div>
</body>

app/views/pages/contact.html.erb
<div class="jumbotron center">

    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <form class="form-horizontal" method="post">
                    <fieldset>
                        <h2><%= image_tag 'girlhead.jpg' %>What's on your mind?<%= image_tag 'boyhead.jpg' %></h2>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-user bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="fname" name="name" type="text" placeholder="First Name" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-user bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="lname" name="name" type="text" placeholder="Last Name" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-envelope-o bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="email" name="email" type="text" placeholder="Email Address" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-pencil-square-o bigicon"></i></span>
                            <div class="col-md-8">
                                <textarea class="form-control" id="message" name="message" placeholder="Enter your massage for us here. We'll get back to you right away!" rows="4"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

<style>
    .header {
        color: #36A0FF;
        font-size: 27px;
        padding: 10px;
    }

    .bigicon {
        font-size: 35px;
        color: #36A0FF;
    }
</style>

app/views/pages/hername.html.erb
<html lang="en">  
  <head> 
	  
 </head>


 <body>
	<div class="jumbotron center">
	<h1><strong>Her name is...</strong>
	 </h1>

    <td><%= image_tag 'girlhead.jpg' %></td>

	 	
	 	<p></p><p></p>

		<input type="text" class="form-control: focus" placeholder="Type her name here">
		</p>
</div>
</body>

app/views/pages/hisname.html.erb
<html lang="en">  
  <head> 
	  
 </head>


 <body>
	<div class="jumbotron center">
	<h1><strong>His name is...</strong>
	 </h1>

    <td><%= image_tag 'boyhead.jpg' %></td>

	 	
	 	<p></p><p></p>

		<!--not sure if this empty submit button is necessary:    <button type="submit" class="btn btn-default"></button> -->

		<input type="text" class="form-control: focus" placeholder="Type his name here">
		
		<!--not sure if this empty submit button is necessary:    <button type="submit" class="btn btn-default"></button> -->

		
</div>
</body>

app/views/pages/home.html.erb
<html lang="en">  
  <head> 
	  
 </head>


 <body>
	<div class="jumbotron center">
	
	<div class="alert alert-success">
		<strong><h3>Hey, writer!</h3>
		<h5>We're making your future experience as delightful as possible. </br></br>
	 	In the meantime, visit us on <%= link_to "Facebook", "https://www.facebook.com/ohmystories" %> for storytelling tips and other fun things! </br></br>
	 	See you soon!</strong></h5>
	</div>

   <h1><strong>Oh My Stories!</strong>
	 </h1>

   <h2>I create the stories of my dreams</h2>
	 
	 	<p>

	  <div class="row">

		<div class="col-xs-6">
			<div class="imagetwist">
				<%= image_tag("dreaming.png") %>
			</div>
			</div>

		<div class="col-xs-6">
			<div class="imageUNtwist">
						<%= image_tag("readsmaller.png") %>
      </div>
		</div>

		</p>
</div>
</body>

app/views/pages/hotels.html.erb
<div class="jumbotron" other-color>
  <h1>What's your favorite Disney resort?</h1>
</div>

<label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1"> Bay Lake Tower at Disney's Contemporary Resort <br><%= image_tag("logo1BLT.jpg", :alt => "BLT") %></br>
</label>
<label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> Disney's All-Star Movies Resort <br><%= image_tag("logo2ASM.jpg", :alt => "ASM") %></br>
</label>
<label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3"> Disney's All-Star Music Resort <br><%= image_tag("logo3ASMu.jpg", :alt => "ASMu") %></br>
</label>
<label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio4" value="option4"> Disney's All-Star Sports Resort <br><%= image_tag("logo4ASS.jpg", :alt => "ASS") %></br>
</label>
<label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio5" value="option5"> Disney's Animal Kingdom Lodge <br><%= image_tag("logo5AKL.jpg", :alt => "AKL") %></br>
</label>
<label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio6" value="option6"> Disney's Animal Kingdom Villas - Jambo House <br><%= image_tag("logo6AKVJ.jpg", :alt => "AKVJ") %></br>
</label>
<label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio7" value="option7"> Disney's Animal Kingdom Villas - Kidani Village<br><%= image_tag("logo7AKVK.jpg", :alt => "AKVK") %></br>
</label>
<label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio8" value="option8"> Disney's Art of Animation Resort<br><%= image_tag("logo8AOA.jpg", :alt => "AOA") %></br>
</label>
<label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio9" value="option9"> Disney's Beach Club Resort <br><%= image_tag("logo9BC.jpg", :alt => "BC") %></br>
</label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio10" value="option10"> Disney's Beach Club Villas <br><%= image_tag("logo10BCV.jpg", :alt => "BCV") %></br>
</label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio11" value="option11"> Disney's BoardWalk Inn <br><%= image_tag("logo11BWI.jpg", :alt => "BWI") %></br>
</label>
</label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio12" value="option12"> Disney's BoardWalk Villas  <br><%= image_tag("logo12BWV.jpg", :alt => "BWV") %></br>
</label>
</label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio13" value="option13"> Disney's Caribbean Beach Resort <br><%= image_tag("logo13CBR.jpg", :alt => "CBR") %></br>
</label>
</label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio14" value="option14"> Disney's Contemporary Resort  <br><%= image_tag("logo14CR.jpg", :alt => "CR") %></br>
</label>
</label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio15" value="option15"> Disney's Coronado Springs Resort  <br><%= image_tag("logo15CSR.jpg", :alt => "CSR") %></br>
</label>
</label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio16" value="option16"> Disney's Grand Floridian Resort &amp; Spa  <br><%= image_tag("logo16GF.jpg", :alt => "GF") %></br>
</label>
</label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio17" value="option17"> Disney's Old Key West Resort <br><%= image_tag("logo17OKW.jpg", :alt => "OKW") %></br>
</label>
</label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio18" value="option18"> Disney's Polynesian Village Resort  <br><%= image_tag("logo18PVR.jpg", :alt => "PVR") %></br>
</label></label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio19" value="option19"> Disney's Pop Century Resort <br><%= image_tag("logo19PCR.jpg", :alt => "PCR") %></br>
</label></label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio20" value="option20"> Disney's Port Orleans Resort - French Quarter <br><%= image_tag("logo20POFQ.jpg", :alt => "POFQ") %></br>
</label></label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio21" value="option21"> Disney's Port Orleans Resort - Riverside <br><%= image_tag("logo21POR.jpg", :alt => "POR") %></br>
</label></label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio22" value="option22"> Disney's Saratoga Springs Resort &amp; Spa <br><%= image_tag("logo22SSR.jpg", :alt => "SSR") %></br>
</label></label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio23" value="option23"> Disney's Wilderness Lodge <br><%= image_tag("logo23WL.jpg", :alt => "WL") %></br>
</label></label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio24" value="option24"> Disney's Yacht Club Resort <br><%= image_tag("logo24YC.jpg", :alt => "YC") %></br>
</label></label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio25" value="option25"> The Cabins at Disney's Fort Wilderness Resort <br><%= image_tag("logo25FWCab.jpg", :alt => "BWI") %></br>
</label></label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio26" value="option26"> The Campsites at Disney's Fort Wilderness Resort <br><%= image_tag("logo26FWCam.jpg", :alt => "BWI") %></br>
</label> 
     </label></label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio27" value="option27"> The Villas at Disney's Grand Floridian Resort &amp; Spa <br><%= image_tag("logo27GFV.jpg", :alt => "GFV") %></br>
</label> </label></label><label class="radio-inline">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio28" value="option28"> The Villas at Disney's Wilderness Lodge<br><%= image_tag("logo28WLV.jpg", :alt => "WLV") %></br>
</label> 
    
    
    
    
    
    

app/views/pages/info.html.erb
<div class="radio">
  <label>
    <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
    Option one is this and that&mdash;be sure to include why it's great
  </label>
</div>
<div class="radio">
  <label>
    <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
    Option two can be something else and selecting it will deselect option one
  </label>
</div>
<div class="radio">
  <label>
    <input type="radio" name="optionsRadios" id="optionsRadios3" value="option3" disabled>
    Option three is disabled
  </label>
</div>

app/views/pages/login.html.erb
		<% if user_signed_in? %>
		<div class="jumbotron center">
			<h1><%= current_user.name %> has so many stories to tell...</h1>
					<label class="radio-inline">
				  <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1"> Abigail Builds a Train <br><%= image_tag("story1.jpg", :alt => "My first story") %></br>
					</label>
					<label class="radio-inline">
				  <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> Sammy and the Lemonade Stand <br><%= image_tag("story2.jpg", :alt => "My second story") %></br>
					</label>
					<p></p>

					<label class="radio-inline">
				  <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> Gregory Visits the Dentist <br><%= image_tag("story2.jpg", :alt => "My fourth story") %></br>
					</label>					
					<label class="radio-inline">
				  <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1"> Elsa's New Baby Brother<br><%= image_tag("story1.jpg", :alt => "My third story") %></br>
					</label>
					<p></p>

					<label class="radio-inline">
				  <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1"> Katie Learns to Read<br><%= image_tag("story1.jpg", :alt => "My third story") %></br>
					</label>
					<label class="radio-inline">
				  <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> Theo Plants a Vegetable Garden <br><%= image_tag("story2.jpg", :alt => "My fourth story") %></br>
					</label>
				</div>
		

		<%else%>

<div class="jumbotron center">
	
	<div class="row">

		<div class="col-xs-6"><h3>Let's read my stories! <%= link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg" %></h3></div>
		
			
	<div class="col-xs-6"><h3>I'm new here! </br><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-lg" %></h3></div>
		
	
</div>
	  </p>

	<%end%>
</div>

app/views/pages/transitions.html.erb
<div id="pt-main" class="pt-perspective">
    <div class="pt-page pt-page-1">
        <h1><span>A collection of</span><strong>Page</strong> Transitions</h1>
    </div>
    <div class="pt-page pt-page-2"><!-- ... --></div>
    <!-- ... -->
</div>

app/views/pins/edit.html.erb
	<div class="jumbotron">
		<h1>Edit Story Page</h1>

<%= render 'form' %>

		<%= link_to 'Show', @pin %> |
		<%= link_to 'Back', pins_path %>
		
</div>

app/views/pins/index.html.erb
<div class="jumbotron">
  
  <div id="pins" class="transitions-enabled">
    <% @pins.each do |pin| %>
      <div class="box panel panel-default">
        
        <%= link_to image_tag(pin.image.url(:medium)), pin %>
        <div class="panel-body">
          <h5><strong><%= pin.description %></strong></h5>
          <h6><%= pin.user.name if pin.user %></h6>

          <% if current_user && (pin.user == current_user) %>
            <div class="actions">
              <h7>
              <%= link_to edit_pin_path(pin) do %>
                <span class="glyphicon glyphicon-edit"></span>Edit&nbsp;&nbsp;
                <% end %>
              
              <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <span class="glyphicon glyphicon-trash"></span>Delete
                <% end %>
              </h7>
            </div>
            <%end%>

        </div>
      </div>
    <% end %>
  </div>

<div class="center"><ul class="pagination pagination-sm">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
 </ul>
</div>

</div>

app/views/pins/show.html.erb
<div class="jumbotron">
	<%= link_to 'Back', pins_path %>

	<div class="row">
		<div class="col-md-offset-2 col-md-8">
			<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @pin.image.url(:medium) %>
			</div>

				<p><h5><center><%= @pin.description %></h5></p>
				<p><h5><strong><center><%= @pin.user.name if @pin.user %></strong></h5></p>
	
				<h5><center>
				<% if @pin.user == current_user %>
	        <%= link_to edit_pin_path(@pin) do %>
	          <span class="glyphicon glyphicon-edit"></span>Edit&nbsp;&nbsp;
	        <% end %>	
				</h5>
</div>
</div>
		</div>
		</div>
		<% end %>	